### PR TITLE
added work report

### LINKED ISSUE #6: Possibility to overwrite work report ots
`DJANGO_WORK_REPORT_PATH` needs to be set and file mounted into container.

We can potentially use https://docs.helm.sh/chart_template_guide/#accessing-files-inside-templates although not sure whether this is enough as work report is a binary file.

### PR DESCRIPTION
**Pull request by strixBE**
fixes #6

### CODE REVIEW

**Review by eyenx — APPROVED** [review]
lgtm

**Comment by hairmare** [comment]
> lgtm

This chart was moved to https://github.com/adfinis-sygroup/helm-charts and we need to cherry-pick it onto that.

The included ots seems to be a version that has a typo so we would need to replace that as well.

**Review by hairmare — CHANGES_REQUESTED** [review]
Cherry-pick onto https://github.com/adfinis-sygroup/helm-charts and replace work report ots file with a version without typos.

image

**Comment by hairmare** [comment]
Moved to https://github.com/adfinis-sygroup/helm-charts/pull/10

**Pull request closed without merging**
