### PR TITLE
Integrate Timed Frontend deployment

### PR DESCRIPTION
**Pull request by sliverc**
Renames backend objects and integrates frontend objects with same naming scheme.

### CODE REVIEW

**Comment by tongpu** [comment]
Am I correct in assuming that the frontend needs to be configured via the WebGUI after it has started? I'm asking because I don't see any specific configuration for it in the chart.

**Comment by hairmare** [comment]
@tongpu AFAIK the frontend doesn't need any config at all. It simply assumes that the backend is proxied at `/api` and all the heavy lifting is done by the backend anyhow.

**Comment by sliverc** [comment]
@tongpu 
As @hairmare mentioned Ingress is configured so `/api` is forwarded to backend. All configuration of application is done in the backend part (database, secrets etc.).

Are there any other comments concerning this PR?

**Comment by tongpu** [comment]
@sliverc No, LGTM.

**Comment by sliverc** [comment]
@tongpu 
Thanks. Can you mark as approved? Otherwise GitHub doesn't allow me to merge (enforce workflow setting we enabled)

**Review by tongpu — APPROVED** [review]
LGTM

**Pull request merged**
